### PR TITLE
Added pandoc-zotxt.lua

### PR DESCRIPTION
**Pull request by odkr**
This is a Lua filter for pandoc that does more or less the same
pandoc-zotxt does. I had hoped for it to be faster than the
original, but it isn't. (I wrongly assumed that I could retrieve
multiple citation items concurrently in Lua; but Pandoc doesn't
support that.) However, it ships with its only dependency, a
JSON library, and doesn't require anything to run but Pandoc
itself. So maybe it's useful for some people.

### CODE REVIEW

**Comment by odkr** [comment]
Thanks! I haven’t yet added support for BetterBibTex though.

**Comment by egh** [comment]
@odkr I'm trying to get the tests to run on this. Everything looks great to me and I really appreciate the work.  I think the test problem is in zotxt but I'm not sure at the moment.

**Comment by odkr** [comment]
Are you referring to the tests in `pandoc-zotxt/tests/test_zotxt.py`? At a first glance, most of the code there appears to be machinery for the tests and there are, correct me if I'm wrong, four test cases: 

1. simple lookup
2. lookup of an accented citation key
3. lookup of a BetterBibTex key
4. lookup of an non-existing key

My test suite covers all of these cases, save for the second one. If that helps I can try to tidy up my test suite a bit and include a similar case. Lua is unicode-agnostic, so there's a very real chance things can break here. (I’m thinking of non-ASCII characters that consist of multiple octets in non-normalised order; but given that Zotero doesn’t normalise strings either, at least it didn’t last time I checked, there is probably not much that can be done about this.)

**Comment by odkr** [comment]
Hey, I recently had a look at the code again. I've cleaned it up a bit and added the feature of letting `pandoc-zotxt.lua` 'manage' JSON bibliography files.

**Comment by odkr** [comment]
Sorry for the noise, but my Lua is rusty, it appears ;).

**Comment by egh** [comment]
I'm sorry this fell off my radar. I'm going to merge now. This is so much better than pandoc-zotxt (python). I'll try to update the README to mention it and deprecate the python code (which I haven't been keeping up-to-date). Thanks again!

**Comment by odkr** [comment]
No worries. (I just found out that there's a one year old PR on one of my repos. It happens.) I've improved the error handling of pandoc-zotxt.lua in the meantime. I'll open a new PR. But that should be it for the time being.

**Pull request merged**
